import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";
import { UserProvider } from "@/context/UserContext";
import { getUser } from "@/lib/getUser";
import LinkTraker from "@/components/thirdParty/LinkTracker";
import { LinkTrackerClient } from "@/components/LinkTracker.client";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();
  return (
    <html lang="en">
      <body className="antialiased bg-gray-50 min-h-screen">
        <UserProvider initialValue={user}>
          <header className="bg-white shadow-md py-4">
            <nav className="max-w-5xl mx-auto px-4 flex justify-between items-center">
              <h1 className="text-xl font-bold text-indigo-600">My App</h1>
              <ul className="flex space-x-6">
                <li>
                  <Link
                    className="text-gray-700 hover:text-indigo-600 font-medium"
                    href="/"
                  >
                    Home
                  </Link>
                </li>
                <li>
                  <Link
                    className="text-gray-700 hover:text-indigo-600 font-medium"
                    href="/admin"
                  >
                    Admin
                  </Link>
                </li>
                <li>
                  <LinkTrackerClient href="/admin">
                    Admin tracker
                  </LinkTrackerClient>
                </li>
              </ul>
            </nav>
          </header>
          <main className="max-w-4xl mx-auto p-6">{children}</main>
        </UserProvider>
      </body>
    </html>
  );
}
